server.port=8080
spring.application.name=bff

services.reportes.url=http://localhost:8081
services.monitoreo.url=http://localhost:8082

resilience4j.circuitbreaker.instances.monitoreo-cb.sliding-window-size=5
resilience4j.circuitbreaker.instances.monitoreo-cb.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.monitoreo-cb.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.monitoreo-cb.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.monitoreo-cb.automatic-transition-from-open-to-half-open-enabled=true

logging.level.io.github.resilience4j=DEBUG
